version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.04  
    steps:
      - checkout

      - restore_cache:
          key: android-orb-v1-

      - run:
          name: Set Gradle permissions
          command: chmod +x ./gradlew

      - run:
          name: Check Java version
          command: java -version 

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Build project
          command: ./gradlew build

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run tests
          command: ./gradlew testDebugUnitTest --continue

      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: favorite/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
